---
abstract: 'Turn your perl upside down'
author:
  - 'David Leadbeater <dgl@dgl.cx>'
build_requires:
  Filter::Simple: 0
  Module::Build: 0.36
  PadWalker: 0
  Text::UpsideDown: 0
  perl: v5.8.9
configure_requires:
  Filter::Simple: 0
  Module::Build: 0.36
  PadWalker: 0
  Text::UpsideDown: 0
  perl: v5.8.9
generated_by: 'Module::Build version 0.3603'
license: wtfpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-ǝmɔA
requires:
  Filter::Simple: 0
  Module::Build: 0.36
  PadWalker: 0
  Text::UpsideDown: 0
  perl: v5.8.9
resources:
  license: ~
version: 1337.1
